### PR TITLE
Can now guess region and service from elastic search service URL's

### PR DESCRIPTION
**Pull request by derek-burdick**

### CODE REVIEW

**Comment by derek-burdick** [comment]
These fixes allow Sign4 to work for AWS ElasticSearch

**Comment by wolfeidau** [comment]
I would love it if this could be merged, also ran into the ES URL requirement.

Cheers.

**Comment by danopia** [comment]
I also had to add an `"es": 4` entry to `awsSignVersion` before the normal flow would work.

**Comment by chiefy** [comment]
LGTM ping @mdwhatcott

**Pull request merged**
